sonar.projectKey=shennawardana23_sonar-cloud-go
sonar.organization=shennawardana23

# Project name and version
sonar.projectName=sonar-cloud-go
sonar.projectVersion=1.0

# Source code location
sonar.sources=.
sonar.exclusions=**/*_test.go,**/vendor/**

# Test file location and coverage report
sonar.tests=.
sonar.test.inclusions=**/*_test.go
sonar.go.coverage.reportPaths=coverage.out

# Encoding of the source code
sonar.sourceEncoding=UTF-8

# Additional Go-specific properties
sonar.go.govet.reportPaths=govet-report.out
sonar.go.golint.reportPaths=golint-report.out
sonar.go.golangci-lint.reportPaths=golangci-lint-report.xml

# Exclude generated files (if any)
# sonar.exclusions=**/generated/**